# 支払記録
CREATE TABLE PAYMENT (
  PAYMENT_ID VARCHAR(36) NOT NULL,
  PAYMENT_AMOUNT INT NOT NULL,
  PAYMENT_TYPE VARCHAR(10) NOT NULL,
  PAYMENT_AT TIMESTAMP NOT NULL,
  PRIMARY KEY (PAYMENT_ID)
);

# 現金入出金
CREATE TABLE CASH_INOUT (
    CASH_INOUT_ID VARCHAR(36) NOT NULL,
    CASH_AMOUNT INT NOT NULL,
    CASH_INOUT_TYPE VARCHAR(10) NOT NULL,
    CASH_INOUT_QUANTITY INT NOT NULL,
    CASH_INOUT_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (CASH_INOUT_ID)
);

# ドリンクマスタ
CREATE TABLE DRINK (
    DRINK_ID VARCHAR(36) NOT NULL,
    DRINK_NAME VARCHAR(20) NOT NULL,
    DRINK_PRICE INT NOT NULL,
    PRIMARY KEY (DRINK_ID)
);

# ドリンクマスタの初期データ
INSERT INTO DRINK (DRINK_ID, DRINK_NAME, DRINK_PRICE) VALUES ("55d49fc7-8c76-4bcb-9357-568700dd0f7a", "コーヒー", 130);

# ドリンク入出庫
CREATE TABLE DRINK_INOUT (
    DRINK_INOUT_ID VARCHAR(36) NOT NULL,
    DRINK_ID VARCHAR(36) NOT NULL,
    DRINK_INOUT_TYPE VARCHAR(10) NOT NULL,
    DRINK_INOUT_QUANTITY INT NOT NULL,
    DRINK_INOUT_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (DRINK_INOUT_ID)
);

# 入出庫の初期データ
INSERT INTO DRINK_INOUT (DRINK_INOUT_ID, DRINK_ID, DRINK_INOUT_TYPE, DRINK_INOUT_QUANTITY, DRINK_INOUT_AT)
VALUES ("1dda8adf-ddfa-4445-b854-a63467893762", "55d49fc7-8c76-4bcb-9357-568700dd0f7a", "IN", 10, "2021-07-29 15:46:39");

# 販売記録
CREATE TABLE DRINK_SOLD (
    SOLD_ID VARCHAR(36) NOT NULL,
    DRINK_ID VARCHAR(36) NOT NULL,
    SOLD_QUANTITY INT NOT NULL,
    SOLD_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (SOLD_ID)
);
